# Generated by Django 4.1.2 on 2022-10-07 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visi_h_ingreso', models.TimeField()),
                ('visi_h_salida', models.TimeField()),
                ('visi_fecha', models.DateField()),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='personas.estudiante')),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='personas.visitante', verbose_name='visitante')),
            ],
        ),
    ]
