# Generated by Django 4.1.2 on 2022-10-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestra',
            name='maes_dependencia',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='maestra',
            name='maes_tipo_estado',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='maestra',
            name='maes_valor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
