# Generated by Django 4.1.2 on 2022-10-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0002_alter_maestra_maes_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestra',
            name='maes_dependencia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='maestra',
            name='maes_tipo_estado',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='maestra',
            name='maes_valor',
            field=models.CharField(max_length=20),
        ),
    ]
