# Generated by Django 4.1.2 on 2022-10-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='pers_apellido',
            field=models.CharField(max_length=20, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pers_identificacion',
            field=models.CharField(max_length=15, verbose_name='Identificacion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pers_nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
