# Generated by Django 4.1.2 on 2022-11-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maestras', '0003_alter_maestra_maes_dependencia_and_more'),
        ('personas', '0002_alter_persona_pers_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_identificacion', to='maestras.maestra'),
        ),
    ]
