# Generated by Django 4.1.2 on 2022-11-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_persona_tipo_identificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualizando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('accion', models.CharField(max_length=10)),
            ],
        ),
    ]
