# Generated by Django 4.1.2 on 2022-11-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_actualizando'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualizando',
            name='pers_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pers_id', to='personas.persona'),
        ),
    ]
